//This file contains all text variables necessary to run the game.
var start_warning = "You have already started the game! Try a different command next time."

var introduction = "<p>"
+ "One morning, in the heat of the Paris summer, we read in the newspaper about a terrible killing. An old woman and her daughter, who had lived alone in an old house "
+ "in the Rue Morgue, had been killed in the middle of the night. <br>"
+ "<blockquote class=\"newspaper_quote\">"
	+ "<em>Paris, July 7, 1840.</em> In the early morning today the people in the western part of the city were awakened from their sleep by cries of terror, which came, it "
	+ "seemed, from a house in the street called the Rue Morgue. The only persons living in the house were an <b>old woman, Mrs. L’Espanaye, and her daughter. Several neighbors "
	+ "and a policeman</b> ran toward the house, but by the time they reached it the cries had stopped. When no one answered their calls, they forced the door open. <br>"
	+ "As they rushed in they heard voices, two voices; they seemed to come from above. The group hurried from room to room, but they found nothing until they reached the "
	+ "<b>fourth floor</b>. There they found a d<b>oor that was firmly closed, locked, with the key inside</b>. Quickly they forced the door open, and they saw spread before them "
	+ "a bloody sickening scene — a scene of horror! <br>"
	+ "The room was in the wildest possible order — broken chairs and tables were lying all around the room. There was only one bed, and from it everything had been "
	+ "taken and thrown into the middle of the floor. <br>"
	+ "There was blood <b>everywhere</b>, on the floor, on the bed, on the walls. A <b>sharp knife covered with blood</b> was lying on the floor. In front of the "
	+ "fireplace there was some <b>long gray hair, also bloody</b>; it seemed to have been pulled from a human head. On the floor were <b>four pieces of gold, an "
	+ "earring, several objects made of silver, and two bags containing a large amount of money in gold.</b> Clothes had been thrown around the room. A box was found "
	+ "under the bed covers. It was open, and held only a few old letters and papers. <br>"
	+ "There was no one there — or so it seemed. <b>Above the fireplace they found the dead body of the daughter</b>; it had been <b>put up into the opening where "
	+ "the smoke escapes to the sky</b>. The body was still warm. There was blood on the face, and on <b>the neck there were dark, deep marks which seemed to have "
	+ "been made by strong fingers.</b> These marks surely show how the daughter was killed. After hunting in every part of the house without finding anything more, "
	+ "the group went outside. <b>Behind the building they found the body of the old woman. Her neck was almost cut through,</b> and when they tried to lift her up, "
	+ "her head fell off."
+ "</blockquote>"
+ "This sounds like our kind of mystery. What should we do?"
+ "</p>";